-- init-databases.sql

CREATE USER dms_user WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'dms_password';

CREATE DATABASE dms OWNER dms_user;
GRANT ALL PRIVILEGES ON DATABASE dms TO dms_user;

CREATE DATABASE filedb OWNER dms_user;
GRANT ALL PRIVILEGES ON DATABASE filedb TO dms_user;

